/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellRouteImport } from './routes/sell'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NameRouteImport } from './routes/$name'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileHelpRouteImport } from './routes/profile/help'
import { Route as ProductNameRouteImport } from './routes/product/$name'
import { Route as PaymentsDoneRouteImport } from './routes/payments/done'
import { Route as CategoryNameRouteImport } from './routes/$category/$name'

const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHelpRoute = ProfileHelpRouteImport.update({
  id: '/profile/help',
  path: '/profile/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductNameRoute = ProductNameRouteImport.update({
  id: '/product/$name',
  path: '/product/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsDoneRoute = PaymentsDoneRouteImport.update({
  id: '/payments/done',
  path: '/payments/done',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryNameRoute = CategoryNameRouteImport.update({
  id: '/$category/$name',
  path: '/$category/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/home': typeof HomeRoute
  '/sell': typeof SellRoute
  '/$category/$name': typeof CategoryNameRoute
  '/payments/done': typeof PaymentsDoneRoute
  '/product/$name': typeof ProductNameRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/home': typeof HomeRoute
  '/sell': typeof SellRoute
  '/$category/$name': typeof CategoryNameRoute
  '/payments/done': typeof PaymentsDoneRoute
  '/product/$name': typeof ProductNameRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/home': typeof HomeRoute
  '/sell': typeof SellRoute
  '/$category/$name': typeof CategoryNameRoute
  '/payments/done': typeof PaymentsDoneRoute
  '/product/$name': typeof ProductNameRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$name'
    | '/home'
    | '/sell'
    | '/$category/$name'
    | '/payments/done'
    | '/product/$name'
    | '/profile/help'
    | '/profile/settings'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$name'
    | '/home'
    | '/sell'
    | '/$category/$name'
    | '/payments/done'
    | '/product/$name'
    | '/profile/help'
    | '/profile/settings'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/$name'
    | '/home'
    | '/sell'
    | '/$category/$name'
    | '/payments/done'
    | '/product/$name'
    | '/profile/help'
    | '/profile/settings'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameRoute: typeof NameRoute
  HomeRoute: typeof HomeRoute
  SellRoute: typeof SellRoute
  CategoryNameRoute: typeof CategoryNameRoute
  PaymentsDoneRoute: typeof PaymentsDoneRoute
  ProductNameRoute: typeof ProductNameRoute
  ProfileHelpRoute: typeof ProfileHelpRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/help': {
      id: '/profile/help'
      path: '/profile/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof ProfileHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$name': {
      id: '/product/$name'
      path: '/product/$name'
      fullPath: '/product/$name'
      preLoaderRoute: typeof ProductNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/done': {
      id: '/payments/done'
      path: '/payments/done'
      fullPath: '/payments/done'
      preLoaderRoute: typeof PaymentsDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$name': {
      id: '/$category/$name'
      path: '/$category/$name'
      fullPath: '/$category/$name'
      preLoaderRoute: typeof CategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameRoute: NameRoute,
  HomeRoute: HomeRoute,
  SellRoute: SellRoute,
  CategoryNameRoute: CategoryNameRoute,
  PaymentsDoneRoute: PaymentsDoneRoute,
  ProductNameRoute: ProductNameRoute,
  ProfileHelpRoute: ProfileHelpRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
